### ISSUE TITLE
Incorrect box removal

### ISSUE THREAD

**Issue by savchenko** [LudoPinelli/comment-box.nvim#35]
Consider the following, `*` indicates cursor position:

```
--[[
 -  ╭────────────────────────────────────────────────────────────────────────────╮
 -  │   *               Plugins related to comment functionality                 │
 -  ╰────────────────────────────────────────────────────────────────────────────╯
]]
```

Executing `:CBd` makes it:

```
--[[
 -  ╭────────────────────────────────────────────────────────────────────────────╮
-- Plugins related to comment functionality
 -  ╰────────────────────────────────────────────────────────────────────────────╯
]]
```

Expected result:

```
-- Plugins related to comment functionality
```

**Comment by LudoPinelli** [comment]
You need to select the box for the command to work correctly. The doc doesn't insist much on this point, I will fix it.
The reason is that the plugin can't detect a box since it depends on the characters used to make it, which can be anything. The way it works is it assumes that non alphanumeric characters have been used and remove them from the start of the line and from the end of the line until it finds an alphanumeric one, leaving just the text.

It's not a perfect solution since it doesn't cover every possibilities (if the comment end with a parenthesis for example, it will be removed, and you will see below that the `*` you put in your example, since it comes before the first alphanumeric character, will be removed!) but I think the result is still better than having to do it entirely manually.

For the example you gave:

```
--[[
 -  ╭────────────────────────────────────────────────────────────────────────────╮
 -  │   *               Plugins related to comment functionality                 │
 -  ╰────────────────────────────────────────────────────────────────────────────╯
]]
```

After selecting the 5 lines (with visual line mode (`Shift+V`)), launching `:CBd` works as intended:

```
--  
-- Plugins related to comment functionality
--  
```

**Comment by LudoPinelli** [comment]
Just for information, I improved the regexes so the common characters (`(){},;.!?:`) that can be found at the beginning or end of a comment won't be removed anymore.
