### ISSUE TITLE
Unnecessary space added if line contains comment char only

### ISSUE THREAD

**Issue by savchenko** [LudoPinelli/comment-box.nvim#39]
`:set ft=bash` and add execute `:CBllline` on an empty commented line.

**Before**

```bash
  #
```

**After**

```bash
# ──  ─────────────────────────────────────────────────────────────────────────────
```

**Comment by LudoPinelli** [comment]
Yes, it's because `:CBllline` is for a titled line (first "l" for the alignement of the line, second "l" for the alignement of the text, then "line", so 3 "l"), it expects that there is a string to align left on the line where the space is.

For a simple full line, the command is `:CBlline` (just 2 "l").

I agree that it's not very intuitive. I will add a check in case there is no text to avoid this behavior, thanks!

**Comment by LudoPinelli** [comment]
Yes. It's not only the space btw, it's also the symbols before and after the text that are put no matter a text is on the line or not (it didn't show in your example because the symbols before and after the text are set to the same symbol as the ont for the line by default).
For example :`CBllline10` without text gives:
```
# ├┤  ├──────────────────────────────────────────────────────────────────┤
```

I'm currently rewriting the plugin from the ground up for the next version, in part because of this kind of poor design choices. The "simple lines" and "titled lines" won't be treated as two different categories.
But it will take some time, I will make a patch for the current version.

**Comment by LudoPinelli** [comment]
Done!

**Comment by LudoPinelli** [comment]
It will be for the the rewritten version, it needs too many changes to be patch for the current one. It's going quite well so far, but I honestly don't know when it will be available.

**Comment by LudoPinelli** [comment]
Sorry, I don't understand what the problem is in your example?
