### ISSUE TITLE
automatically display comments or docstring in boxes as virtual text

### ISSUE THREAD

**Issue by quantum-booty** [LudoPinelli/comment-box.nvim#5]
Rather than having to manually convert comments or docstring to boxes, it would be nice to have option to automatically display them in boxes as virtual text. That way you don't modify the source code.

**Comment by LudoPinelli** [comment]
I'm rather new to Neovim and lua, and I had no idea it was something possible. I will definitely look into it!

**Comment by yyy33** [comment]
I don't think this is a good opinion, if you do so in other editors to read will not see the effect

**Comment by tingham** [comment]
Yeah not having other people see it would not be so great but, on the other hand, scarcity breeds value. :) I think it would be a really cool option to have.

**Comment by Integralist** [comment]
Would be great if instead of permanently persisting the changes to the comments, to instead have it be just a visual thing for while the buffer is open. Not sure if that's the same thing being suggested here. Basically, I'd love to have my comments visually _rendered_ in a box but I don't want the source files _actually_ changed to that format.

**Comment by LudoPinelli** [comment]
> Would be great if instead of permanently persisting the changes to the comments, to instead have it be just a visual thing for while the buffer is open. Not sure if that's the same thing being suggested here. Basically, I'd love to have my comments visually _rendered_ in a box but I don't want the source files _actually_ changed to that format.

Yes, it would be a nice option to have. I'll look into it!
